# Generated by Django 5.2.1 on 2025-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="benefits",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="duration",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                blank=True,
                help_text="e.g. Full-time, Part-time, Contract",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
